server {
    # 80番ポートで待ち受ける
    listen 80;
    # URLの最後にファイル名がなければindex.phpを探す
    index index.php index.html;
    # webサイトのファイルがあるディレクトリ
    root /var/www/html/public;

    location / {
        # URLに対応するファイルを順番に探す
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # PHPの処理はappコンテナの9000番ポートに繋ぐ
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}